openapi: 3.0.3
info:
  title: Device Management Service API
  version: 1.0.0

paths:
  /devices:
    post:
      summary: Регистрация нового устройства
      description: Регистрирует устройство и привязывает его к дому.
      operationId: createDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - device_type_id
                - house_id
                - serial_number
              properties:
                device_type_id:
                  type: string
                house_id:
                  type: string
                serial_number:
                  type: string
                name:
                  type: string
      responses:
        "201":
          description: Устройство создано
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        "400":
          description: Некорректные данные запроса
        "409":
          description: Конфликт — устройство уже существует
        "500":
          description: Внутренняя ошибка сервера

  /devices/{id}:
    get:
      summary: Получение информации об устройстве
      operationId: getDevice
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Информация об устройстве
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        "404":
          description: Устройство не найдено
        "500":
          description: Внутренняя ошибка сервера

  /devices/{id}/command:
    post:
      summary: Отправка команды устройству
      operationId: sendCommand
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - command
              properties:
                command:
                  type: string
                payload:
                  type: object
                  additionalProperties: true
      responses:
        "202":
          description: Команда принята
          content:
            application/json:
              schema:
                type: object
                properties:
                  device_id:
                    type: string
                  command:
                    type: string
                  status:
                    type: string
                  queued_at:
                    type: string
                    format: date-time
        "400":
          description: Ошибка запроса
        "404":
          description: Устройство не найдено
        "500":
          description: Внутренняя ошибка сервера

components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
        device_type_id:
          type: string
        house_id:
          type: string
        serial_number:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [online, offline, unknown]
        last_seen_at:
          type: string
          format: date-time
        firmware_version:
          type: string
