openapi: 3.0.3
info:
  title: Gates Service API
  version: 1.0.0

paths:
  /gates/{device_id}/open:
    post:
      summary: Открыть ворота
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "202":
          description: Ворота открываются
        "404":
          description: Устройство не найдено

  /gates/{device_id}/close:
    post:
      summary: Закрыть ворота
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "202":
          description: Ворота закрываются
        "404":
          description: Устройство не найдено
