openapi: 3.0.3
info:
  title: Lighting Service API
  version: 1.0.0

paths:
  /lighting/{device_id}/switch:
    post:
      summary: Включение или выключение света
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: string
                  enum: [on, off]
      responses:
        "202":
          description: Команда выполнена
        "404":
          description: Устройство не найдено
