openapi: 3.0.3
info:
  title: Scenario Service API
  version: 1.0.0

paths:
  /scenarios:
    post:
      summary: Создание сценария автоматизации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                house_id:
                  type: string
                name:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      device_id:
                        type: string
                      metric_type:
                        type: string
                      operator:
                        type: string
                      value:
                        type: string
                actions:
                  type: array
                  items:
                    type: object
                    properties:
                      target_device_id:
                        type: string
                      command:
                        type: string
                      command_payload:
                        type: object
                        additionalProperties: true
      responses:
        "201":
          description: Сценарий создан
        "400":
          description: Ошибка в данных запроса
